site_name: System Design Primer Update  
theme:
  name: material
  language: en
  custom_dir: overrides/
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search               # MkDocs default search plugin
  - git-revision-date-localized:
      type: date         # or datetime, iso_date, iso_datetime, timeago
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
        - index.md
  - i18n:
      default_language: en
      languages:
        en: English
  # - htmlproofer


extra:
  giscus:
    repo: ido777/system-design-primer-update
    repo_id: R_kgDOORdCfw
    category: "Feedback by Page"
    category_id: DIC_kwDOORdCf84CqLEY
    mapping: pathname
    reactions_enabled: 1
    emit_metadata: 0
    input_position: bottom
    theme: light
    lang: en
    loading: lazy

extra_javascript:
  - js/client-debug.js
  - js/giscus-debug.js


markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

nav:
  - Home: en/index.md
  - About: https://github.com/ido777/system-design-primer-update/blob/main/README.md
  - Contributing: https://github.com/ido777/system-design-primer-update/blob/main/CONTRIBUTING.md
  - License: https://github.com/ido777/system-design-primer-update/blob/main/LICENSE.md
  - Changelog: https://github.com/ido777/system-design-primer-update/blob/main/CHANGELOG.md

  - English:
      - Overview: en/index.md
      - Study Guide Start Here: en/study_guide.md
      - System Design Interview Questions: en/solutions.md
      - System Design at a Glance: en/design-glance.md
      - System Design Interview Questions:
          - System Design:
              - Pastebin: docs/solutions/system_design/pastebin/README.md
              - Query Cache: docs/solutions/system_design/query_cache/README.md
              - Mint: docs/solutions/system_design/mint/README.md
              - Sales Rank: docs/solutions/system_design/sales_rank/README.md
              - URL Shortener: docs/solutions/system_design/url_shortener/README.md
              - Web Crawler: docs/solutions/system_design/web_crawler/README.md
              - Scaling AWS: docs/solutions/system_design/scaling_aws/README.md
              - Social Graph: docs/solutions/system_design/social_graph/README.md
              - Twitter: docs/solutions/system_design/twitter/README.md
          - Object-Oriented Design:
              - Call Center: docs/solutions/object_oriented_design/call_center/README.md
              - Circular Array: docs/solutions/object_oriented_design/circular_array/README.md
              - Deck of Cards: docs/solutions/object_oriented_design/deck_of_cards/README.md
              - Hash Table: docs/solutions/object_oriented_design/hash_table/README.md
              - LRU Cache: docs/solutions/object_oriented_design/lru_cache/README.md
              - Movie Tickets: docs/solutions/object_oriented_design/movie_tickets/README.md
              - Online Chat: docs/solutions/object_oriented_design/online_chat/README.md
              - Parking Lot: docs/solutions/object_oriented_design/parking_lot/README.md

  - Translations (Not up to date):
    - 简体中文 (Simplified Chinese):
        - 简体中文主页: zh/design-glance.md

    - 繁體中文 (Traditional Chinese):
        - 繁體中文首頁: zh-Hant/design-glance.md

    - العربية (Arabic):
        - الصفحة الرئيسية: ar/design-glance.md

    - 日本語 (Japanese):
        - 日本語のホーム: ja/design-glance.md

    - Türkçe (Turkish):
        - Türkçe Anasayfa: tr/design-glance.md
