site_name: System Design Primer Update  
site_url: https://ido777.github.io/system-design-primer-update/en/study_guide/

repo_url: https://github.com/ido777/system-design-primer-update
repo_name: ido777/system-design-primer-update

# use_directory_urls: true

theme:
  name: material
  language: en
  custom_dir: overrides/
  features:
    - navigation.tabs
    - navigation.tabs.sticky    
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch 
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path    
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.suggest
    - toc.follow    
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins:
  # - i18n:
  #     default_language: en
  #     languages:
  #       - locale: en
  #         name: English
  #         default: true
  #       - locale: zh
  #         name: Simplified Chinese
  #       - locale: zh-Hant
  #         name: Traditional Chinese
  #       - locale: ja
  #         name: Japanese
  #       - locale: tr
  #         name: Turkish
  #       - locale: ar
  #         name: Arabic
  - search               # MkDocs default search plugin
  - git-revision-date-localized:
      type: date         # or datetime, iso_date, iso_datetime, timeago
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
        - index.md
  - git-committers:
      repository: ido777/system-design-primer-update
      branch: main
  - meta
  - offline
  # - htmlproofer

extra:
  analytics:
    provider: google
    property: UA-210436000-1
  giscus:
    repo: ido777/system-design-primer-update
    repo_id: R_kgDOORdCfw
    category: "Feedback by Page"
    category_id: DIC_kwDOORdCf84CqLEY
    mapping: pathname
    reactions_enabled: 1
    emit_metadata: 0
    input_position: bottom
    theme: light
    lang: en
    loading: lazy
  # alternate:
  # - name: English
  #   link: en/index.md 
  #   lang: en
  # - name: 简体中文
  #   link: /zh/
  #   lang: zh
  # - name: 繁體中文
  #   link: /zh-Hant/
  #   lang: zh-Hant
  # - name: 日本語
  #   link: /ja/
  #   lang: ja

extra_javascript:
  - javascripts/client-debug.js
  - javascripts/giscus-debug.js

extra_css:
  - stylesheets/default.css


markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

nav:
  - Home: en/index.md
  - About: https://github.com/ido777/system-design-primer-update/blob/main/README.md
  - Contributing: https://github.com/ido777/system-design-primer-update/blob/main/CONTRIBUTING.md
  - License: https://github.com/ido777/system-design-primer-update/blob/main/LICENSE.md
  - Changelog: https://github.com/ido777/system-design-primer-update/blob/main/CHANGELOG.md
  - English:
      - Overview: en/index.md
      - Study Guide Start Here: en/study_guide.md
      - System Design Interview Questions: en/practice.md
      - System Design at a Glance: en/design-glance.md
      - System Design Solutions:
          - Pastebin: solutions/system_design/pastebin/README.md
          - Query Cache: solutions/system_design/query_cache/README.md
          - Mint: solutions/system_design/mint/README.md
          - Sales Rank: solutions/system_design/sales_rank/README.md
          - URL Shortener: solutions/system_design/url_shortener/README.md
          - Web Crawler: solutions/system_design/web_crawler/README.md
          - Scaling AWS: solutions/system_design/scaling_aws/README.md
          - Social Graph: solutions/system_design/social_graph/README.md
          - Twitter: solutions/system_design/twitter/README.md
      - Object-Oriented Design Solutions:
          - Call Center: solutions/object_oriented_design/call_center/README.md
          - Circular Array: solutions/object_oriented_design/circular_array/README.md
          - Deck of Cards: solutions/object_oriented_design/deck_of_cards/README.md
          - Hash Table: solutions/object_oriented_design/hash_table/README.md
          - LRU Cache: solutions/object_oriented_design/lru_cache/README.md
          - Movie Tickets: solutions/object_oriented_design/movie_tickets/README.md
          - Online Chat: solutions/object_oriented_design/online_chat/README.md
          - Parking Lot: solutions/object_oriented_design/parking_lot/README.md

  - Translations (Not up to date):
    - 简体中文 (Simplified Chinese):
        - 简体中文主页: zh/design-glance.md

    - 繁體中文 (Traditional Chinese):
        - 繁體中文首頁: zh-Hant/design-glance.md

    - العربية (Arabic):
        - الصفحة الرئيسية: ar/design-glance.md

    - 日本語 (Japanese):
        - 日本語のホーム: ja/design-glance.md

    - Türkçe (Turkish):
        - Türkçe Anasayfa: tr/design-glance.md
